// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqiQkK2K1UFcGdN_MU_rs_0DsJquw08T8',
    appId: '1:664728281581:web:946b721304c02d7c0e07e4',
    messagingSenderId: '664728281581',
    projectId: 'uyaniklik-takibi',
    authDomain: 'uyaniklik-takibi.firebaseapp.com',
    storageBucket: 'uyaniklik-takibi.appspot.com',
    measurementId: 'G-GPN7VB6H37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2EgVrqikUK_8zdX6Ca3uf2EHbjuvVfcI',
    appId: '1:664728281581:android:086cbeffdccba45b0e07e4',
    messagingSenderId: '664728281581',
    projectId: 'uyaniklik-takibi',
    storageBucket: 'uyaniklik-takibi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYBxtapjxugU2G3EP4KnisI-Go1CIbol0',
    appId: '1:664728281581:ios:693db4469bc05bed0e07e4',
    messagingSenderId: '664728281581',
    projectId: 'uyaniklik-takibi',
    storageBucket: 'uyaniklik-takibi.appspot.com',
    iosClientId: '664728281581-mp8ssb9ncnr9elk3bgvueb8bj8a29bsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.uyaniklikTakibi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYBxtapjxugU2G3EP4KnisI-Go1CIbol0',
    appId: '1:664728281581:ios:693db4469bc05bed0e07e4',
    messagingSenderId: '664728281581',
    projectId: 'uyaniklik-takibi',
    storageBucket: 'uyaniklik-takibi.appspot.com',
    iosClientId: '664728281581-mp8ssb9ncnr9elk3bgvueb8bj8a29bsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.uyaniklikTakibi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqiQkK2K1UFcGdN_MU_rs_0DsJquw08T8',
    appId: '1:664728281581:web:7b55788a938a46b00e07e4',
    messagingSenderId: '664728281581',
    projectId: 'uyaniklik-takibi',
    authDomain: 'uyaniklik-takibi.firebaseapp.com',
    storageBucket: 'uyaniklik-takibi.appspot.com',
    measurementId: 'G-XL9WWD4CDD',
  );
}
